; Use to set the parameters of the game.
; Parsed very simply... just ints in order.
; Recommend not deleting comments so you remember what they are :)

; max # of years from today
1000

; allow BC
0

; allow future years
0
